### ISSUE TITLE
Oversampling module results to satellite's pixels

### ISSUE THREAD

**Issue by zxdawn** [Kang-Sun-CfA/Oversampling_matlab#1]
Hi Kang @Kang-Sun-CfA ,

Your repository is very useful for resampling data.

Now, I'm trying to resample 3D model profiles to satellite pixels like TROPOMI, or reversely.
Does your method also work for this situation?

It seems you're updating the `popy.py` recently, is that the main script of oversampling now?

Thanks,
Xin

**Comment by Kang-Sun-CfA** [comment]
Hi Xin,

Every 3D model would be different. I attempted to do that in
popy.F_interp_profile, which is a wrapper around F_interp_gcrs. It only
works for one version of GEOS-Chem. Feel free to add more.

Kang

**Comment by zxdawn** [comment]
@Kang-Sun-CfA 
Thanks, Kang!

I will take a look at that function later.
Hope I can make some contributions ;)

Regards,
Xin

**Comment by zxdawn** [comment]
@Kang-Sun-CfA 
Hi Kang,

I read the `pop.py` today and have one question about the `sounding_ps`.
You use the surface pressure from reanalysis data to recalculate the pressures at each model level.

If we set different model levels, the `Ap` and `Bp` need to be changed in the `F_interp_gcrs` function, right?
So, why not using `RegularGridInterpolator` (the method of calculating the `gc_gas_doy`) to get pressures at the model levels over pixels?

Could tell me the advantage of using surface pressure from reanalysis data, instead of the pressure  in the model?

Thanks,
Xin

**Comment by Kang-Sun-CfA** [comment]
Hi Xin,

In this GEOS-Chem model I got from someone else, the pressure levels were
not saved. The GC pressure levels are inherited from the reanalysis
(MERRA-2 in this case), and they are terrain-following, i.e., the pressure
levels are different for different surface pressure, not a uniform grid
across the domain. Hence in this case I have to recover the pressure levels
using MERRA-2 surface pressure and GC Ap/Bp. For many other models, the
concentrations are defined at regular lat/lon/pressure grids, the
interpolation would be easier.

Kang

**Comment by zxdawn** [comment]
@Kang-Sun-CfA 
Hi Kang,

Thank you for your explanation.
WRF-Chem is similar to GEOS-Chem. It supports the terrain following (TF) vertical coordinate and hybrid vertical coordinate (HVC). I've finished the interpolation draft for WRF-Chem using the pressure variable in the output file.

As the GEOS-Chem resolution is lower than that of OMI/TROPOMI data, it's OK to use the simple interpolation.
For the high resolution (<= 1km) model like WRF-Chem, is it better to use a weight function for resampling the simulation to pixels?

BTW, I checked the [resampling method](https://github.com/CohenBerkeleyLab/BEHR-core-utils/blob/440e28e66911dc2ad0a18e525fb1796591750a59/AMF_tools/rProfile_WRF.m#L251) in the BEHR product. They use the `tessellation` approach as mentioned in your paper but without weight.

Since my purpose is replacing the a priori profiles in each pixel like that in the BEHR, is it necessary to use the physical resampling (which doesn't support resampling to pixels)? or just calculate the average of grids in pixels with weight based on overlapped area?
,
Xin

**Comment by zxdawn** [comment]
`xarray` just added the [`weighted` function](https://github.com/pydata/xarray/pull/2922) 3 days ago!
It may be useful to combine our own weights with xarray function.

BTW, I also used the `interp` function of xarray in `interp_profile`, like this:
```
sounding_profile = wc_gas_t.interp(west_east=x, south_north=y).transpose()
sounding_pEdge = wc_p_t.interp(west_east=x, south_north=y).transpose()
```

**Comment by Kang-Sun-CfA** [comment]
Hi Xin,

If your model is <= 1km, you can average profiles on all model grids within
one OMI pixel. For TROPOMI, you may want to use tessellation or my spatial
response function to calculate the weight for each profile on the model
grid.

Kang

**Comment by zxdawn** [comment]
@Kang-Sun-CfA 
Hi Kang,

Thanks for your suggestion.

The resolution of my model is 1 km. I've tried the `area_weighted` in xESMF.
It works well:
![image](https://user-images.githubusercontent.com/30388627/77876585-fbdcf480-7285-11ea-9790-fbd8bb7b9e78.png)
