### ISSUE TITLE
version problem

### ISSUE THREAD

**Issue by TTBean** [Kang-Sun-CfA/Oversampling_matlab#7]
what is recommended version of python for mair_o2dp?

**Comment by TTBean** [comment]
cause i've suffered from problem 'AttributeError: 'dict' object has no attribute '__dict__' when running popy.py

**Comment by Kang-Sun-CfA** [comment]
Can you locate at which line this error happened? I've been using Python 3.6+

**Comment by TTBean** [comment]
> 
i met this problem when using function F_wrapper_l3, the error happend at line270
--> 270         l3_data = l3_data.merge(l3_data0)
